openapi: 3.0.0
info:
  title: ECOM
  version: 1.0.0
servers:
  - url: http://localhost:5050
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: MASTER
  - name: LOCATION
  - name: ENTITIES
  - name: ROLES
paths:
  /api/master/forgot-password:
    post:
      tags:
        - MASTER
      summary: FORGOT PASSWORD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: samirkumar2527@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/verification:
    post:
      tags:
        - MASTER
      summary: VERIFICATION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: samirkumar2527@gmail.com
                token: "627166"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/user-id/d69d2bce-ad9a-4685-b391-ea6dcbf133b0:
    get:
      tags:
        - MASTER
      summary: USER BY ID
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/login:
    post:
      tags:
        - MASTER
      summary: LOGIN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userName: admin
                password: admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/set-password:
    post:
      tags:
        - MASTER
      summary: SET PASSWORD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: samirkumar2527@gmail.com
                password: admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master:
    get:
      tags:
        - MASTER
      summary: GET ALL MASTER DATA
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/:
    post:
      tags:
        - MASTER
      summary: CREATE MASTER USER
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userName: admin2
                email: admin2@gmail.com
                firstName: admin
                lastName: admin
                mobile: "7079583248"
                roles: 071e921d-d08f-4d7f-84a9-c00d4409d774
                isActive: 1
                isDeleted: 0
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - MASTER
      summary: UPDATE MASTER USER
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: e2fe259d-8cda-44c7-a7a9-9339c2c6805f
                userName: admin2
                email: admin2@gmail.com
                firstName: admin
                lastName: admin
                mobile: "7079583248"
                roles: 071e921d-d08f-4d7f-84a9-c00d4409d774
                isActive: 1
                isDeleted: 0
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/check-if-exists:
    post:
      tags:
        - MASTER
      summary: CHECK IF USER EXISTS
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: email
                value: samirkumar2527@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/location:
    get:
      tags:
        - LOCATION
      summary: GET LOCATION
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - LOCATION
      summary: DELETE LOCATION
      parameters:
        - name: id
          in: query
          schema:
            type: string
          example: d0bc643a-7512-47b0-a4b2-4a609df2e223
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - LOCATION
      summary: CREATE LOCATION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: T1
                city: Buxar
                state: Bihar
                country: Bharat
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - LOCATION
      summary: UPDATE LOCATION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: d0bc643a-7512-47b0-a4b2-4a609df2e223
                name: Dumri5
                city: Buxar
                state: Bihar
                country: Bharat
                delete: false
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/entity:
    get:
      tags:
        - ENTITIES
      summary: GET ALL ENTITIES
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - ENTITIES
      summary: CREATE ENTITY
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Bharat Prasad General Store
                gst: 10DKQPP6909G1ZX
                address: Dumri, Buxar, Bihar
                location_id: 92dd3112-e37c-425b-a588-d60b55a5e0de
                proprietor_name: Ashok Prasad
                categories:
                  - Grocery
                  - Cosmetics
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/entity/4ba3eaca-a83d-4bf6-bbc2-0a263b7a65f0:
    get:
      tags:
        - ENTITIES
      summary: GET ENTITY BY ID
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - ENTITIES
      summary: UPDATE ENTITY
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: TEST
                gst: TEST
                address: TEST
                location_id: 92dd3112-e37c-425b-a588-d60b55a5e0de
                proprietor_name: TEST
                categories:
                  - Grocery
                  - Cosmetics
                  - ELECTRICAL
                is_active: true
                max_admin: 5
                max_manager: 7
                delete: false
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - ENTITIES
      summary: DELETE ENTITY
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/entity/location/92dd3112-e37c-425b-a588-d60b55a5e0de:
    get:
      tags:
        - ENTITIES
      summary: GET ENTITY BY LOCATION ID
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/master/roles:
    get:
      tags:
        - ROLES
      summary: GET ALL ROLES
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
